# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LYN' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LYN

 pod 'Firebase'
 pod 'Firebase/Messaging'

  target 'LYN-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LYNTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'LYN-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LYN-tvOS

end
